### ISSUE TITLE
Meta: Client API feature request summary

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#656]
This is a meta issue that summarizes all the current API related feature requests and attempts to organize them and give some extra commentary. I plan to update this issue with new requests and when existing ones are closed.

## File Metadata
- [ ] Client API: Change Archive/Inbox and Trash state for files #393
  - This seems fairly simple and would be very useful immediately for a number of existing uses of the API.
- [ ] Use BlurHash in Hydrus #394
- [ ] Client API: notes #346
  - This would probably involve being able to (perhaps optionally) get the notes of a file through the metadata API or a separate API and another API for setting the notes on a file.
- [ ] Client API: more file metadata #345
  - Time imported and whatever other metadata is not currently returned by the file_metadata endpoint
  - May need to be behind another query parameter for performance if some metadata needs to be calculated before being returned.

## Search
The existing file search in the API is very limited compared to what's possible in the full client. The main things needed are sorting, the `system:` predicates, and wildcard support. 

- [ ] Client API: searching and sorting via system predicates #351
- [ ] Sorting in API search #236
- [ ] Client API: Search wildcards #654

## Pages
- [ ] Client API: page and query management #350
- [ ] API: Change page contents #570 

## Tags
While there are API endpoints for editing tags on files there are none for querying the tags themselves. Currently client applications must figure out what tags exist through the tags in file metadata, this means the results for autocomplete and such are limited. The first two issues below are generally about ways of getting tag information that would be useful for autocomplete and other functions. The last two issues are more about allowing API clients to display tags closer to how Hydrus itself does, namely namespace colors and siblings.

- [ ] Expose favourite tags via API #311
- [ ] Client API: tags with use counts per service #359
- [ ] Client API: read/write tag presentation details #360
- [ ] Client API: Apply siblings on retrieved tags #389

## URLs
- [ ] Feature:API:Search URLs by prefix #240
- [ ] Client API: Ability to lookup an array of URLs in `get_url_info` and `get_url_files` #655

## Other
- [ ] Client API: get information about services #342
- [ ] Client API: subscriptions #344 
- [ ] Client API: ratings #343
- [ ] Client API: alternates/duplicates #347
- [ ] Generate QR codes for Apps #237
- [ ] Client API: manage headers (like cookies) #349
- [ ] Add DB Lock feature to the Client side #333
- [ ] Popup notification for when things are added through API #559
- [ ] Client API Revision #247
- [ ] Cache for API requests #605

**Comment by luckydonald** [comment]
I have no idea why #343 is 404. I'd love to look into it.
For that I'd also research how #351, was done, but that's gone, too.

**Comment by floogulinc** [comment]
@luckydonald the guy who made those issues was banned from GitHub. You can still access older versions of those pages on the Wayback Machine for example. 

Ratings are not supported in the search API at this time. You can see examples of possible system predicates in the [API docs](https://hydrusnetwork.github.io/hydrus/developer_api.html). Most of the system predicate stuff for the API is implemented here: https://github.com/hydrusnetwork/hydrus/blob/master/hydrus/external/SystemPredicateParser.py
